### PR TITLE
feat: updates comments to reflect new comments in theme generator script

### PR DESCRIPTION
**Pull request by markconroy**

### CODE REVIEW

**Comment by finnlewis** [comment]
Hey @markconroy 

Just saw this, quick question, is it that we are not using Oswald for the localgov_scarfolk theme? So we were previously including a font that was not used? 

Have I understood that right?

Cheers!

Finn

**Comment by markconroy** [comment]
We were never using Oswald in this theme (though it was being added and loaded and shouldn't have been). That line in the CSS was supposed to just be a demo of "how" to add a font in a CSS file.

**Comment by markconroy** [comment]
The fonts being used in localgov_scarfolk are all defined in the html.html.twig file, which is better for performance. That's basically what the updated comments here are saying too.

**Comment by justinepocock** [comment]
These comments do now match what's on localgov_base

**Pull request merged**
